# Returns square of elements in Python using Generator function

def square_number(lst):
    for i in lst:
        yield i**2


lst = [1, 2, 3, 4, 5, 6]

result = square_number(lst)

# Since for loop understand how many times it need to run loop, we can use for loop to print the numbers returned by generated by generator function.
for i in result:
    print (i)
